config/routes.rb
Rails.application.routes.draw do
  root "flights#index"
  resources :bookings, only: [:new, :create, :show]
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :departing_flights, class_name: "Flight", foreign_key: "departing_airport_id"
  has_many :arriving_flights, class_name: "Flight", foreign_key: "arriving_airport_id"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  has_many :passengers, dependent: :destroy

  accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :departing_airport, class_name: "Airport"
  belongs_to :arriving_airport, class_name: "Airport"
  has_many :bookings
  has_many :passengers, through: :bookings

  def takeoff_string
    self.takeoff.strftime("%Y-%m-%d")
  end

  def self.takeoff_strings
    self.order(:takeoff).map(&:takeoff_string).uniq
  end

  def self.search(params)
    return [] if params.empty?
    self.where("departing_airport_id = :departing_airport_id AND arriving_airport_id = :arriving_airport_id AND DATE(takeoff) = :takeoff", params.to_h)
  end
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  belongs_to :booking
  has_one :flight, through: :booking
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @flight = Flight.find(booking_params[:flight_id])
    @booking = @flight.bookings.new
    booking_params[:passenger_count].to_i.times { @booking.passengers.new }
  end

  def create
    @booking = Booking.new(booking_params)
    if @booking.save
      @booking.passengers.each do |passenger|
        PassengerMailer.with(passenger: passenger, booking: @booking).ticket_booked_email.deliver_later
      end
      redirect_to @booking
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @booking = Booking.find(params[:id])
  end

  private
  def booking_params
    params.require(:booking).permit(:flight_id, :passenger_count, passengers_attributes: [:name, :email])
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @flights = Flight.search(flight_search_params)
  end

  private
  def flight_search_params
    params.permit(:departing_airport_id, :arriving_airport_id, :takeoff, :passenger_count)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/new.html.erb
<h1>Booking for flight #<%= @flight.id %></h1>
<%= render "flights/info", flight: @flight %>
<%= form_with model: @booking, url: bookings_path do |f| %>
  <div data-controller="list" data-list-item-count-value="-1">
    <button data-action="list#addItem">&nbsp;&nbsp;<b>+</b> Add Passenger&nbsp;&nbsp;</button><br>
    <template data-list-target="itemTemplate">
      <button data-list-target="removeBtn" data-action="list#remove">&nbsp;&nbsp;<b>-</b>&nbsp;&nbsp;</button>
      <%= f.fields_for "passengers_attributes", index: "INDEXNUM" do |passenger_form| %>
          <%= passenger_form.label :name, "Passenger Name: " %>
          <%= passenger_form.text_field :name %>
          <%= passenger_form.label :email, "Passenger Email: " %>
          <%= passenger_form.text_field :email %>
      <% end %>
      <br>
    </template>
    <% @booking.passengers.length.times do %>
      <div data-list-target="listItem"></div>
    <% end %>
  </div>
  <%= f.hidden_field "flight_id", value: params[:booking][:flight_id] %>
  <%= f.submit "Submit Flight Booking" %>
<% end %>

app/views/bookings/show.html.erb
<h2>Booking #<%= @booking.id %> on Flight #<%= @booking.flight.id %></h2>
<%= render "flights/info", flight: @booking.flight %>
<%= render @booking.passengers %>

app/views/flights/_flight.html.erb
<input type="radio" name="booking[flight_id]" value="<%= flight.id %>" id="flight_id_<%= flight.id %>">
<label for="flight_id_<%= flight.id %>">
  <p>From: <i><%= flight.departing_airport.text_code %></i> | To: <i><%= flight.arriving_airport.text_code %></i></p>
  <p>Departure: <i><%= flight.takeoff.to_fs(:long) %></i></p>
  <p>Flight Duration: <i><%= flight.duration_minutes %> min</i></p>
</label>

app/views/flights/_info.html.erb
<h3><i><%= flight.departing_airport.text_code %></i> to <i><%= flight.arriving_airport.text_code %></i> @ <i><%= flight.takeoff.to_fs(:long) %></i></h3>

app/views/flights/index.html.erb
<h1>Find a flight!</h1>
<%= form_with method: :get do |f| %>
  <%= f.label :departing_airport_id, "Departure: " %>
  <%= f.collection_select(:departing_airport_id, Airport.all, :id, :text_code) %>
  <%= f.label :arriving_airport_id, "Destination: " %>
  <%= f.collection_select(:arriving_airport_id, Airport.all, :id, :text_code) %>
  <%= f.label :passenger_count, "Passenger Count:" %>
  <%= f.select :passenger_count, [1,2,3,4] %>
  <%= f.label :takeoff, "Take Off:" %>
  <%= f.select(:takeoff, Flight.takeoff_strings) %>
  <%= f.submit "Search" %>
<% end %>
<%= form_with url: new_booking_path, method: :get do |f| %>
  <div id="flight_radio_list">
    <%= render @flights %>
  </div>
  <%= f.hidden_field "booking[passenger_count]", value: params[:passenger_count] %>
  <%= f.submit "Book Flight" unless @flights.empty? %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFlightBooker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/passengers/_passenger.html.erb
<p><b>Passenger #<%= passenger_counter + 1 %></b><br>Name: <%= passenger.name %><br>E-Mail: <%= passenger.email %></p>